cache:
  paths:
    - vendor/

before_script:
  # Install dependencies
  - bash ci/docker_install.sh > /dev/null
  # Install composer dependencies
  - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
  - php composer.phar install


# We test PHP8.0 
test:8.0:
  image: php:8.0
  script:
    - phpunit --configuration phpunit.xml
