before_script:
  # Install dependencies
  - bash ci/docker_install.sh > /dev/null

# We test PHP5.6
test:5.6:
  image: php:5.6
  script:
    - phpunit --configuration phpunit.xml

# We test PHP8.0 
test:8.0:
  image: php:8.0
  script:
    - phpunit --configuration phpunit.xml