version: '3.5'

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    env_file:
      - .env


  db:
    image: mysql:5.6
    platform: linux/x86_64
    volumes:
      - "./.docker/mysql/:/var/lib/mysql"
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
