version: '3.5'

services:

  app:
    container_name: lumen
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    env_file:
      - .env


  db:
    container_name: db
    image: mysql:8.0
    platform: linux/x86_64
    volumes:
      - "./.docker/mysql/:/var/lib/mysql"
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"